# Generated by Django 3.0.4 on 2020-03-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('test_size', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ranking', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop', models.CharField(default='billa', max_length=100)),
                ('item_number', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('nutrition_fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nutrition_saturated_fatty_acids', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nutrition_sugar', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nutrition_salt', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_fiber', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_mono_unsaturated_fatty_acids', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_poly_unsaturated_fatty_acids', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_natrium', models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.ManyToManyField(through='server.Details', to='server.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Experiment')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Part')),
                ('products', models.ManyToManyField(to='server.Product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.IngredientType'),
        ),
        migrations.AddField(
            model_name='details',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Ingredient'),
        ),
        migrations.AddField(
            model_name='details',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Part'),
        ),
        migrations.AddField(
            model_name='details',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Recipe'),
        ),
    ]
