# Generated by Django 3.0.4 on 2020-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop', models.CharField(default='billa', max_length=100)),
                ('item_number', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('nutrition_fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nutrition_saturated_fatty_acids', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nutrition_sugar', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nutrition_salt', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_fiber', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_mono_unsaturated_fatty_acids', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_poly_unsaturated_fatty_acids', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nutrition_calcium', models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True)),
                ('nutrition_natrium', models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True)),
            ],
        ),
    ]
