# Generated by Django 3.0.5 on 2020-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition_calcium',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True),
        ),
    ]
