# Generated by Django 3.0.4 on 2020-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200330_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='macro_fatty_acids',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='macro_salt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='macro_sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='macro_carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='macro_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='macro_protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
